import Link from "next/link";
import { ArrowUpRight, Code2, Layers3, Sparkles, Zap } from "lucide-react";
import { Button, Footer, Navbar, Reveal } from "./components";

const services = [
  { icon: <Layers3 />, number: "01", title: "Websites that work", text: "Clear, conversion-minded websites for businesses ready to look as capable as they are." },
  { icon: <Code2 />, number: "02", title: "Apps with purpose", text: "Useful web applications that turn complex workflows into simple, confident moments." },
  { icon: <Zap />, number: "03", title: "Speed by default", text: "Thoughtful engineering that keeps every interaction fast, accessible and ready to grow." },
];

export default function Home() {
  return <><Navbar /><main>
    <section className="hero section-shell">
      <div className="hero-copy"><Reveal><p className="eyebrow"><span className="pulse-dot" /> Independent web studio · Kolkata, India</p><h1>Digital products with <em>momentum.</em></h1><p className="hero-lede">Stackmorphic builds modern websites and web applications for businesses that want to move with clarity.</p><div className="hero-actions"><Button href="/contact">Start a project <ArrowUpRight /></Button><Link className="text-link" href="/projects">See selected work <span>↗</span></Link></div></Reveal></div>
      <Reveal delay="delay-2"><div className="hero-console" aria-label="Interactive development preview"><div className="console-bar"><span className="window-dots"><i /><i /><i /></span><span>stackmorphic / studio</span><span className="live-label"><b /> live</span></div><div className="console-body"><div className="code-column"><span className="code-comment">// create a better web</span><span><b className="pink">const</b> <strong>experience</strong> = {'{'}</span><span className="indent"><b className="cyan">intent</b>: <i>&quot;clarity&quot;</i>,</span><span className="indent"><b className="cyan">pace</b>: <i>&quot;fast&quot;</i>,</span><span className="indent"><b className="cyan">impact</b>: <i>&quot;measurable&quot;</i></span><span>{'}'}</span><span className="code-cursor">_</span></div><div className="preview-column"><div className="preview-heading"><span>performance</span><b>98</b></div><div className="metric-line"><span /><span /><span /></div><div className="preview-card"><div className="tiny-orb">✦</div><div><small>your next</small><strong>big move</strong></div><ArrowUpRight /></div><div className="preview-foot"><span>responsive</span><span>accessible</span><span>ready</span></div></div></div></div></Reveal>
    </section>
    <section className="statement section-shell"><Reveal><p className="eyebrow">01 / The point of view</p><h2>Good technology should feel <span>obvious.</span></h2><p className="section-intro">No noise. No mystery. Just thoughtful design and dependable engineering shaped around the people your business serves.</p></Reveal></section>
    <section className="service-section section-shell"><div className="section-head"><div><p className="eyebrow">02 / What we do</p><h2>Built for the <em>next chapter.</em></h2></div><Link className="round-arrow" href="/services" aria-label="Explore services">↗</Link></div><div className="service-grid">{services.map((service, index) => <Reveal key={service.number} delay={`delay-${index + 1}`}><article className="service-card"><div className="card-top"><span>{service.number}</span><span className="service-icon">{service.icon}</span></div><h3>{service.title}</h3><p>{service.text}</p><Link href="/services">Explore service <span>→</span></Link></article></Reveal>)}</div></section>
    <section className="project-feature section-shell"><Reveal><div className="section-head"><div><p className="eyebrow">03 / Concept work</p><h2>Ideas, made <em>real.</em></h2></div><Link className="text-link" href="/projects">View all concepts <span>↗</span></Link></div><Link className="feature-art" href="/projects"><div className="feature-copy"><span className="tag">Concept / E-commerce</span><h3>Made to be<br /><em>remembered.</em></h3><span className="feature-cta">Open project <ArrowUpRight /></span></div><div className="feature-shape"><div className="shape-label">OBJECT<br /><b>01</b></div><div className="shape-disc" /></div></Link></Reveal></section>
    <section className="cta-band section-shell"><Reveal><Sparkles /><h2>Have a good problem?</h2><p>Tell us what you&apos;re building. We&apos;ll help you find the next right step.</p><Button href="/contact">Let&apos;s talk <ArrowUpRight /></Button></Reveal></section>
  </main><Footer /></>;
}
